### ISSUE TITLE
OSS DB Tools - Error

### ISSUE THREAD

**Issue by klaud-ctrl** [microsoft/azuredatastudio-postgresql#266] opened 2021-04-06 10:28 UTC
Hi there, Im running into an error and I cant connect to my pg server on azure. Can you help out here?

![screenshot](https://user-images.githubusercontent.com/55669588/113697335-57c92d00-96d3-11eb-8c5b-c2625027af3a.png)

**Comment by iFoton** [comment] 2021-04-08 05:41
Got same issue. Windows Server 2019.

**Comment by iFoton** [comment] 2021-04-08 06:02
There is [solution](https://github.com/microsoft/azuredatastudio-postgresql/issues/252). In brief you have to install Microsoft Visual C++ 2015 Redistributable Update 3 RC.

**Comment by DaeunYim** [comment] 2021-09-23 18:00
Duplicate of https://github.com/microsoft/azuredatastudio-postgresql/issues/252. Closing the issue.

**Closed by DaeunYim** 2021-09-23 18:00 UTC
Labels: bug, GA
