### ISSUE TITLE
exception occured when bytea field selected

### ISSUE THREAD

**Issue by itn3000** [microsoft/azuredatastudio-postgresql#103] opened 2019-03-22 04:55 UTC
# Overview

When I executed sql query to table including bytea field, following error occured and all fields are filled with empty value.

# Environment

* client
    * OS: windows-8.1 x64
    * Azure Data Studio: 1.5.1
    * PostgreSQL Extension: 0.1.0
* server
    * OS: windows server 2016
    * postgresql(from `select version()`): PostgreSQL 9.6.1, compiled by Visual C++ build 1800, 64-bit

# Steps to reproduce

1. connect any existing postgresql database server
2. create new database
3. reconnect to newly created database
4. run following sql query

```sql
select version();
-- ensure using initialized table
drop table if exists bintable;
-- creating test table
create table bintable(a bytea);
-- inserting binary data
insert into bintable(a)values(decode('aa', 'hex'));
-- select from 
select * from bintable
```

# Expected result

get query result including binary field.

# Actual result

column was displayed, but value is empty,
and following error was displayed on "OUTPUT" window.

```
[Error - 1:30:38 PM] Request query/subset failed.
  Message: Unhandled exception while handling request method query/subset: "'utf-8' codec can't decode byte 0xa2 in position 1: invalid start byte"
  Code: -32603 
```

**Comment by Shin-Aska** [comment] 2019-07-03 11:05
Can confirm that this bug is still present on the latest stable version of Windows 10

Version: 1.8.0 (system setup)
Commit: 96e214593190071f0b520439929b218f9fa673de
Date: 2019-06-06T01:59:30.203Z
VS Code 1.34.0
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

**Comment by swjain23** [comment] 2020-03-03 19:35
Duplicate of #155

**Comment by sergei-b** [comment] 2020-03-04 00:12
It would also be beneficial to know these values:
```
show server_encoding;
show client_encoding;
show bytea_output;
show lc_collate;
show lc_ctype;
```

**Comment by sergei-b** [comment] 2020-03-04 22:12
Can you confirm that this issue is still present with the current version of the extension (0.2.4)? We could not reproduce it. If it still reproducible in your environment, please also run the script from the previous comment and attach the result.

**Comment by itn3000** [comment] 2020-03-05 00:13
I've tested same query with azuredatastudio-postgresql-0.2.4, and sql query's result was displayed successfuly as I expected.

**Closed** 2020-04-20 20:55 UTC
Labels: bug
