### ISSUE TITLE
Server panel does not list items

### ISSUE THREAD

**Issue by gkbrown22** [microsoft/azuredatastudio-postgresql#174] opened 2019-11-28 21:15 UTC
Here's the error:
  Code: -32603 
[Error - 10:02:36 PM] Request connection/listdatabases failed.
  Message: Unhandled exception while handling request method connection/listdatabases: "connection already closed"
  Code: -32603 

But the SQL window still responds. The connection is not closed. 
Using a proxy connection to connect to cloud DB in this case.

**Comment by nahk-ivanov** [comment] 2020-01-08 22:30
Seems like a duplicate of #99 .

**Comment by swjain23** [comment] 2020-07-29 18:36
Fixed by microsoft/pgtoolsservice#252

**Closed by swjain23** 2020-07-29 18:36 UTC
