### ISSUE TITLE
Message "Failed to start Pgsql tools service" appeared in MacOS

### ISSUE THREAD

**Issue by gctrevino** [microsoft/azuredatastudio-postgresql#349] opened 2023-02-09 17:04 UTC
- Azure Data Studio Version: 1.41.1 Apple Silicon
- OS Version: MacOS Monterey Version 12.6

Steps to Reproduce:

1. Install Azure Data Studio Version 1.40.1
2. Install PostgreSQL extension (v0.2.7) through the Extension Manager following instructions from https://learn.microsoft.com/en-us/sql/azure-data-studio/extensions/postgres-extension
3. Popup appears with message "Failed to start Pgsql tools service". 

![image](https://user-images.githubusercontent.com/5189445/217883365-05b226ab-7461-428f-bd0b-893751a1c30f.png)

There is no further information in the popup nor in the developer tools window, this started happening when I reinstalled Azure Data Studio with the latest release. 

As a temporary fix, I downgraded the installation to version 1.39.1, the extension works correctly in that version.

Does this issue occur when all extensions are disabled?: No

**Comment by alanrenmsft** [comment] 2023-02-09 21:52
@gctrevino Instead of downgrading you could also use the Intel version of latest ADS release.

**Comment by pbgc** [comment] 2023-02-11 15:11
duplicate of #345 #346 and #347 ......

**Comment by awaitJosh** [comment] 2023-02-12 22:54
> @gctrevino Instead of downgrading you could also use the Intel version of latest ADS release.

If I install version 1.39.1 first, install the plugin and update after installing the plugin, the error doesn't occur. So starting with version 1.39.1 and updating afterwards might be slightly better..?

**Comment by luisrudge** [comment] 2023-03-10 05:33
@awaitJosh sorry for the silly question, but how can I find the link for the 1.39.1 version?

**Comment by alanrenmsft** [comment] 2023-03-10 06:24
@luisrudge https://github.com/microsoft/azuredatastudio/releases/tag/1.39.1

**Comment by luisrudge** [comment] 2023-03-10 17:26
@alanrenmsft thanks! unfortunately, there's no m1 version in there, only the intel version :(

**Comment by alanrenmsft** [comment] 2023-03-10 17:53
@luisrudge yes, that is unfortunate, the PG extension team hasn't started working on the arm64 support yet. BTW, you don't have to use 1.39.1, you can use the latest Intel version, I think that works too.

**Comment by luisrudge** [comment] 2023-03-10 17:55
@alanrenmsft sounds good. Yeah, that message made me believe that upgrading from 1.39.1 would work on arm64, but it doesn't. Unfortunately the intel version is unusably slow.

**Comment by DaeunYim** [comment] 2023-05-19 19:53
Tracking from https://github.com/microsoft/azuredatastudio-postgresql/issues/356. Closing this issue

**Closed by DaeunYim** 2023-05-19 19:53 UTC
