### ISSUE TITLE
Certain tables are no longer queryable

### ISSUE THREAD

**Issue by wehnertb** [microsoft/azuredatastudio-postgresql#437] opened 2023-07-18 14:25 UTC
**Describe the bug**
So I was querying my database today (db: customers, table: "Accounts").  Everything is fine.  Updated plugin to v0.4.2 and now I get a "None" response when trying to query the table.  I can query every other table in DB, just this one will not return any results.

**To Reproduce**
1. Update plugin to v0.4.2
2. Connect to Database (Azure PostgreSQL Single Server v11)
3. select "customers" database
4. select * from "Accounts" limit 10;

**Expected behavior**
Expect to see first 10 results from query, instead I get:

9:22:56 AMStarted executing query at Line 1
None
Total execution time: 00:00:00.030

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 Version 22H2 (OS Build 22621.1702)

**ADS (please complete the following information):**
 - 1.44.1
- v0.4.2
- PostgreSQL version 11 (Azure PostgreSQL Single Server)

**Additional context**
v0.3.1 did not have this problem, only going to versions v0.4.0 and higher cause issue.

**Comment by DaeunYim** [comment] 2023-07-19 21:22
Hi, although we haven't been able to reproduce this issue on our end, we suspect it might be related to the psycopg version upgrade we introduced in version 0.4. To ensure compatibility with the latest version, could you please try the following steps?

Navigate to C:\Users<user_name>.azuredatastudio\extensions and clear out any existing PostgreSQL extensions. (Don't worry about losing your connection info, they will appear once you re-install the extension)

Open your file explorer, go to the %temp% location, and remove any folders named _MEI<6digit number> if they exist.

Once you've completed these steps, please try downloading and installing the new version of the PostgreSQL extension again.

Please let us know if this resolves the issue or if you need further assistance.

**Comment by DaeunYim** [comment] 2023-07-19 22:13
Hi, thanks for reporting this issue. 

We were unable to reproduce this error from our end. I attempted an AAD connection to an Azure PostgreSQL server on both Windows 10 and 11, using ADS PG extensions 0.3 and 0.4, as well as ADS version 1.44 and previous versions. 

However, there have been some new binaries introduced in the 0.4 version, and we suspect they may be related to the issue. Could you please follow the steps below to clean up your environment?

Navigate to "C:\Users<user_name>.azuredatastudio\extensions" and delete any existing PostgreSQL extensions. Don't worry about losing your connection information, as they will reappear once you reinstall the extension.

Open your file explorer and go to the "%temp%" location. Remove any folders named "_MEI<6digit number>" if they exist.

Once you have completed these steps, please try downloading and installing the new version of the PostgreSQL extension again.

Please let us know if this resolves the issue or if you need any further assistance.

**Comment by nasc17** [comment] 2023-07-25 21:18
Hello, please inform us if steps outlined by Daeun were able to resolve your issue.
We would also appreciate your verification if issue is persistent in latest unstable release of PostgreSQL extension v0.4.3-insiders.

**Comment by jqing** [comment] 2023-07-27 13:30
I have similar errors like this. suddenly the query return no result. following is what I have tried.

table users has 188 records

`select * from users` - no result
`select * from users limit 100` - no result
`select * from users order by id limit 100` - **show result**
`select * from users order by id limit 200` - no result 
`select * from users order by id` - no result

and finally I found out that one field in the table causing this. table users has a field call CreateTime with datatype timestamptz, if this field is not include in the query or been convert to a text, it works as expected.

which means
`select id from users` - **show result**
`select id, "CreateTime"  from users` - no result
`select id, "CreateTime"::text  from users` - **show reault**

this only happens on my PC. my team number's works fine. 

I will try Daeun's suggestion and report back.

**Comment by jqing** [comment] 2023-07-27 14:16
tried Daeun's suggestion. no difference.

**Comment by nasc17** [comment] 2023-07-27 14:23
> tried Daeun's suggestion. no difference.

Thank you for taking the time to give us more detail about what is triggering this bug.
Can you please inform us what platform, PG version, and extension version you are using?

We currently have an insiders release out now that you can test against as well to see if issue is still present with our newer updates: https://github.com/microsoft/azuredatastudio-postgresql/releases/tag/v0.4.3-insiders

**Comment by jqing** [comment] 2023-07-27 16:28
> > tried Daeun's suggestion. no difference.
> 
> Thank you for taking the time to give us more detail about what is triggering this bug. Can you please inform us what platform, PG version, and extension version you are using?
> 
> We currently have an insiders release out now that you can test against as well to see if issue is still present with our newer updates: https://github.com/microsoft/azuredatastudio-postgresql/releases/tag/v0.4.3-insiders

install the insider version, no luck
>Name: PostgreSQL
Id: Microsoft.azuredatastudio-postgresql
Description: PostgreSQL extension for Azure Data Studio
Version: 0.4.3
Publisher: Microsoft

**Comment by DaeunYim** [comment] 2023-07-28 19:41
Hello @jqing, I'm assuming you were using different datestyle than ISO format.

Our PostgreSQL extension relies on the psycopg Python library to connect to PostgreSQL servers. According to the o[fficial psycopg documentation,](https://www.psycopg.org/psycopg3/docs/basic/adapt.html#datestyle-and-intervalstyle-limits) unless the connection is explicitly configured to accept a specific date format at the initialization stage, the library will default to working with data in the ISO format.

At this point in time, we believe it is in the best interest of the product to maintain this behavior. While we understand that this might pose some inconvenience, we are currently not prioritizing changes to this functionality.

Running this query will temporarily fix the issue. 
SET DATESTYLE = 'ISO, MDY';

**Comment by jqing** [comment] 2023-07-31 12:33
> Hello @jqing, I'm assuming you were using different datestyle than ISO format.
> 
> Our PostgreSQL extension relies on the psycopg Python library to connect to PostgreSQL servers. According to the [official psycopg documentation,](https://www.psycopg.org/psycopg3/docs/basic/adapt.html#datestyle-and-intervalstyle-limits) unless the connection is explicitly configured to accept a specific date format at the initialization stage, the library will default to working with data in the ISO format.
> 
> At this point in time, we believe it is in the best interest of the product to maintain this behavior. While we understand that this might pose some inconvenience, we are currently not prioritizing changes to this functionality.
> 
> Running this query will temporarily fix the issue. SET DATESTYLE = 'ISO, MDY';

is this the new changed in 0.4.2? it didn't happen before.

**Comment by jqing** [comment] 2023-07-31 13:39
hope this can help. after look into the value in users table, I noticed that there are some record stored as `0001-01-01T00:00:00+00:00`, that might be the issue.

**Comment by GennadNY** [comment] 2023-08-03 17:23
Closing for now, need better error handling in case of this issue.

**Closed** 2023-08-14 17:01 UTC

**Comment by DaeunYim** [comment] 2023-08-14 18:30
@wehnertb we found out this could be possibly due to the extreme PG datetime values such as 'infinity' that can't be converted into Python datetime object. We are working on the fix for the next release.

**Comment by dferretti** [comment] 2023-11-01 18:40
@DaeunYim it does look to be related to that - I get the same error if I just run
```sql
select 'infinity'::timestamptz
```
