### ISSUE TITLE
An empty string is shown in the results as being a NULL.

### ISSUE THREAD

**Issue by ami-levin** [microsoft/azuredatastudio-postgresql#236] opened 2020-07-07 01:30 UTC
- Azure Data Studio Version: 1.19.0

Steps to Reproduce:

Open a connection to PostgreSQL and Execute the query: 
SELECT NULL, '';

The result is:
Column1 | Column2
NULL       | NULL

Expected result is:
Column1 | Column2
NULL       | 

An empty string is not a NULL. An empty string is a valid string value.
NULL is a state that indicates a missing value.

For SQL Server the same query returns the correct results.

**Comment by tastyeggs** [comment] 2021-06-01 07:08
Hello. Is there any update on this issue? It's a serious flaw, and causes us to waste time wondering why the queries aren't working, when in fact they are, but the result pane is displaying incorrect results. I'm surprised that no progress has been made on this in the last year, is this extension still maintained?

**Comment by DaeunYim** [comment] 2021-09-23 16:43
Duplicate of https://github.com/microsoft/azuredatastudio-postgresql/issues/143. Closing the issue.

**Closed by DaeunYim** 2021-09-23 16:43 UTC
Labels: bug, M1
