### ISSUE TITLE
Empty string incorrectly shown as null in the data grid

### ISSUE THREAD

**Issue by srulandhs** [microsoft/azuredatastudio-postgresql#168] opened 2019-10-04 17:18 UTC
Postgres SQL v0.2.2

If you run simple SQL statement such as the following, the second column will show as _NULL_ when it should be an empty string. PGAdmin 4 correctly shows the column as an empty string.

Ex: select 1, ''

**Comment by nahk-ivanov** [comment] 2020-01-08 23:06
Duplicate of #143.

**Comment by DaeunYim** [comment] 2021-09-23 16:43
Duplicate of https://github.com/microsoft/azuredatastudio-postgresql/issues/143. Closing the issue.

**Closed by DaeunYim** 2021-09-23 16:43 UTC
Labels: bug, GA, M1
