### ISSUE TITLE
Cannot backup from Azure PostgreSQL

### ISSUE THREAD

**Issue by mflps** [microsoft/azuredatastudio-postgresql#223] opened 2020-06-10 18:22 UTC
Hi I'm trying to backup, but I receive this error:
Backup: pg_dump: server version: 10.11; pg_dump version: 9.6.3
pg_dump: aborting because of server version mismatch

**Comment by swjain23** [comment] 2020-07-15 21:16
Duplicate of #115

**Comment by DaeunYim** [comment] 2021-08-09 21:37
Fixed by https://github.com/microsoft/pgtoolsservice/pull/273

**Closed by DaeunYim** 2021-08-09 21:37 UTC
