### ISSUE TITLE
PostgreSQL extension can't script Create Table

### ISSUE THREAD

**Issue by bonjo** [microsoft/azuredatastudio-postgresql#225] opened 2020-06-22 15:33 UTC
Hi
I'm using Azure Data Studio Insiders with PostgreSQL extension, when I try to generate a script using: script as create option menu, I obtain the following message in pgSQLToolsService console.

> [Error - 10:14:26 AM] Request scripting/script failed.
>   Message: column rel.relhasoids does not exist
> LINE 8:   pg_get_userbyid(rel.relowner) AS relowner, rel.relhasoids,
>                                                      ^
> 
>   Code: 0 
> [object Object]

Here are the details of Azure Data Studio that i'm using
Version: 1.19.0-insider (user setup)
Commit: b922fc7d7a769a7ce1aa5f95aa48c4951c233925
Date: 2020-06-16T05:24:47.444Z
VS Code: 1.46.0
Electron: 7.3.0
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by swjain23** [comment] 2020-07-15 21:32
@bonjo Hi, what version of the extension are you using? Also, what is your PG server version?

**Comment by swjain23** [comment] 2020-07-15 21:37
Able to repro using PG 12. It is happening because the column relhasoids has been dropped from the system catalog pg_class in PostgreSQL v12, because the long deprecated WITH OIDS clause has been removed from CREATE TABLE.

**Comment by mosqueteiro** [comment] 2020-07-15 22:45
PostgreSQL extension: 0.2.6

Sever config
GCP Cloud SQL
PostgreSQL 11

**Comment by bonjo** [comment] 2020-07-16 02:10
> @bonjo Hi, what version of the extension are you using? Also, what is your PG server version?

PG 12.2
PG Extension 0.26

**Comment by e2ibrobbins** [comment] 2020-09-10 13:50
I also get the same error.  I am using PG 12.4 and PG Extension 0.2.6

**Comment by adontz** [comment] 2020-10-30 18:16
https://stackoverflow.com/questions/58461178/how-to-fix-error-column-c-relhasoids-does-not-exist-in-postgres

This look related.

**Comment by pdbenbow** [comment] 2020-11-18 17:30
I'm getting this same error.

PostgreSQL 13.1
psql client 13.1
Azure Data Studio 1.24.0
PostgreSQL extension for Azure Data Studio 0.2.6

> [Error - 11:27:26 AM] Request scripting/script failed.
>   Message: column rel.relhasoids does not exist
> LINE 8:   pg_get_userbyid(rel.relowner) AS relowner, rel.relhasoids,

**Comment by veikkoeeva** [comment] 2021-02-11 18:03
@adontz It looks like. Also https://dba.stackexchange.com/questions/270921/error-column-rel-relhasoids-does-not-exist-with-postgresql-12-and-pgadmin-4-3 that tells it was removed from PostgreSQL and a newer version of pgAdmin is recommended for the asker.

I have this problem with 1.25.3 (latest as of this writing). Can't script tables (a related problem that can't see columns in tables?).

**Comment by daghb** [comment] 2021-06-22 12:36
Still a problem

**Comment by johngrant** [comment] 2021-08-24 16:09
When will this fixed be released?

**Comment by DaeunYim** [comment] 2021-08-25 05:22
> When will this fixed be released?

Hello, I'm tentatively thinking the next release will be 9/1.

**Comment by DaeunYim** [comment] 2021-09-02 00:59
> > When will this fixed be released?
> 
> Hello, the next release will be 9/1.

Please expect delay for this version.

**Comment by dzsquared** [comment] 2021-11-20 22:33
PG extension 0.2.7
postgres 14

can't script as create or drop

**Comment by johngrant** [comment] 2021-11-22 17:13
Could this be fixed by settings the correct `pgsql.debugSourcePath` in preferences? I suspect this is a database version and tools mismatch.

**Comment by louis77** [comment] 2021-11-24 12:37
Having this error to for scripting tables and materialized views. This error is open for almost 1.5 years now. Would be great if there will be a fix released soon!

**Comment by elfalem** [comment] 2021-12-01 17:37
@DaeunYim I noticed that this issue was tagged with `GA` milestone which was planned to be due yesterday. Just wondering if there are any updates.

**Comment by wehnertb** [comment] 2022-08-15 13:34
Any word on whether this will be resolved?  I'm on PostgreSQL 14 and ADS 1.38, PostgreSQL Plugin 0.2.7

**Comment by bohdan-kolomiiets** [comment] 2022-08-19 20:52
Any updates, continue face with this problem for a long time. Could you please investige teams' time ?

**Comment by cab0** [comment] 2022-09-28 13:23
Also looking for an update on this, as I am experiencing the same issue.

**Comment by digital88** [comment] 2023-03-22 08:20
I'm also experiencing this issue as of March 2023

**Comment by malv007** [comment] 2023-04-02 16:38
Any updates on this?

**Closed** 2023-05-30 14:58 UTC
Labels: bug, Release-v0.3

**Comment by elfalem** [comment] 2023-06-14 18:28
I have confirmed that "script as create" is now working for me. Thank you!
