### ISSUE TITLE
unable to connect to PostgreSQL; spins forever

### ISSUE THREAD

**Issue by Maxhodges** [microsoft/azuredatastudio-postgresql#347] opened 2023-02-04 05:01 UTC
- Azure Data Studio Version:  Version: 1.41.1
Commit: 33dce95b152227c4f10f6251ab30690fe9895c0c
Date: 2023-01-28T00:47:32.573Z (1 wk ago)
VS Code: 1.67.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.2.0
- OS Version:13.1 (22C65)

Steps to Reproduce:

1. enter postgres credentials
2.click connect
3. spins forever
4. seems like the app could benefit from a "test connection" button.

Does this issue occur when all extensions are disabled?: Yes/no
I only have one extension -- the postgres connection extension. I can't disable that because without it I can only configure SQL connections.

![screenshot 2023-02-04 at 14 33 27@2x](https://user-images.githubusercontent.com/957271/216750685-66965924-bff3-404a-95f4-8ed8a094eb0a.png)

**Comment by PureKrome** [comment] 2023-03-10 00:20
@Maxhodges any Postgres server. Right now, I have it running on localhost and I can connect .. but I can't see any DB's or do anything because of bugs - confirmed by other users in this GH repo/project:

REF:
- https://github.com/microsoft/azuredatastudio-postgresql/issues/353
- https://github.com/microsoft/azuredatastudio-postgresql/issues/352

**Comment by DaeunYim** [comment] 2023-05-19 19:54
Tracking from https://github.com/microsoft/azuredatastudio-postgresql/issues/356. Closing this issue

**Closed** 2023-05-19 19:58 UTC
