### ISSUE TITLE
Crash on startup in Ubuntu 20.04

### ISSUE THREAD

**Issue by rfuhrer** [microsoft/azuredatastudio-postgresql#218] opened 2020-05-12 18:38 UTC
I'm running a fresh install of Ubuntu 20.04 (actually PopOS 20.04) and when I open up Azure Data Studio it gives me a warning that the postgreSQL plugin has crashed.  I've tried uninstalling and re-installing the extension and as soon as you reinstall and it tries to start up, it crashes.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/usr/local/lib/python3.6/dist-packages/cx_Freeze/initscripts/Console.py", line 26, in run
  File "pgsqltoolsservice/pgtoolsservice_main.py", line 11, in <module>
  File "/usr/local/lib/python3.6/dist-packages/ptvsd/__init__.py", line 17, in <module>
  File "/usr/local/lib/python3.6/dist-packages/ptvsd/attach_server.py", line 35, in <module>
  File "/usr/local/lib/python3.6/dist-packages/ptvsd/visualstudio_py_debugger.py", line 24, in <module>
  File "/usr/lib/python3.6/ctypes/__init__.py", line 7, in <module>
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
[Error - 12:27:28 p.m.] Connection to server got closed. Server will not be restarted.
```
Is there some way of seeing what file it is trying to open?  Maybe it's a permission issue?

Thanks!

**Comment by Nidzo-Vidic** [comment] 2020-05-14 07:27
I'm having the same issue on Kubuntu 20.04. Could the issue be rather with the PostgreSQL tools service than with the extension?

**Comment by Nidzo-Vidic** [comment] 2020-05-15 23:02
So if anyone is interested in a workaround. Sorry for the lengthy description.

So far I've come to the conclusion that the pgtoolsservice is the culprit here.

I've found that it has some issues with psycopg2 version 2.7.5 in the requirements.txt in the pgtoolsservice repository.

In my case I've changed it to psycopg2==2.8, built it, and copied the files to the
pgtoolsservice direcotry (it is beeing downloaded by the PostgreSQL extension).

Here is the process:

Clone the repository

```
git@github.com:microsoft/pgtoolsservice.git
```

Change the psycop2 version from 2.7.5 to 2.8 in the requirements.txt file.

Create a virtual environment in pgtoolsservice directory and activate it, install the requirements and build it.

```
python3 -m venv myenv

source myenv/bin/activate

pip3 install -r requirements.txt

./scripts/build-linux.sh
```

After the build script you have a new build directory. In my case it was

```
buil/exe.linux-x86_64.3.8/
    lib
    pg_exes
    pgtoolsservice_main
```

Now copy lib, pg_exes and pgtoolsservice_main from the build, paste everything and replace to the following directory (on linux it's in the home directory)

```
~/..azuredatastudio/extensions/microsoft.azuredatastudio-postgresql-0.2.6/out/pgsqltoolsservice/Linux/v1.4.0/pgsqltoolsservice
```

After those steps the extension worked again. I hope it helps.

**Comment by sighphyre** [comment] 2020-08-18 10:36
Fresh install of PopOS 20.04 today and had the same problem. ndz-v's super helpful instructions took me most of the way there. Sadly the pgtoolsservice code has been updated and no longer works out the box. For anyone trying to get this to work, you can checkout commit ID: 45ca2267ed7f0e41ce001588408df53f1bc3ffae in the pgtoolservice and follow ndzv's instructions against that

**Comment by dingobar** [comment] 2020-09-11 08:05
The issue seems to be resolved after uninstalling the extension,
```
sudo apt update && apt upgrade -y
```
and reinstalling the extension.

**Comment by Callum-W** [comment] 2020-10-15 01:26
> Here is the process:
> 
> Clone the repository
> 
> ```
> git@github.com:microsoft/pgtoolsservice.git
> ```
> 
> Change the psycop2 version from 2.7.5 to 2.8 in the requirements.txt file.
> 
> Create a virtual environment in pgtoolsservice directory and activate it, install the requirements and build it.
> 
> ```
> python3 -m venv myenv
> 
> source myenv/bin/activate
> 
> pip3 install -r requirements.txt

I attempted this solution and the process repeatedly failed when attempting to the the last command quoted.  Installing the libffi6_3.2.1-8_amd64.deb package solved the problem instantly for me.

**Comment by Callum-W** [comment] 2020-10-15 01:32
I tried numerous solutions to get this to work 

- Uninstalling and reinstalling pyenv,
- Installing the 3.6.12 version of python through pyenv
- Following g0josh's solution

What ended up working was directly installing the libffi6_3.2.1-8_amd64.deb package from;

http://mirrors.kernel.org/ubuntu/pool/main/libf/libffi/libffi6_3.2.1-8_amd64.deb

and installing it with;

`sudo apt install ./libffi6_3.2.1-8_amd64.deb`

Azure Data Studio ran correctly with no errors after installing this package.

I found the solution here from user "antisa"
https://stackoverflow.com/questions/61875869/ubuntu-20-04-upgrade-python-missing-libffi-so-6

**Comment by bengunur06** [comment] 2021-05-19 18:16
Also worked for me https://github.com/microsoft/azuredatastudio-postgresql/issues/218#issuecomment-695926733

**Comment by mksuni** [comment] 2021-09-17 18:39
Closing the issue since we are unable to reproduce it

**Closed by mksuni** 2021-09-17 18:39 UTC
Labels: wontfix

**Comment by shvamabps** [comment] 2021-11-06 08:19
Also worked for me #218 (comment)
