### ISSUE TITLE
second excite of query takes forever

### ISSUE THREAD

**Issue by AhmedHemdan21** [microsoft/azuredatastudio-postgresql#125] opened 2019-05-09 09:21 UTC
Issue Type: <b>Bug</b>

when i try to query table for example 

> select * from table1

, it runs fine and it gets data in 1 seconds 
but when i try to run it again "F5" it doesn't get data and i have to close the tab and re-open another one

Azure Data Studio version: azuredatastudio 1.7.0 (e1280022d69b651cfff04b30e830904575c8acda, 2019-05-08T00:55:40.928Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (4.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by AhmedHemdan21** [comment] 2019-05-09 09:40
after restart Azure Data Studio and retested, i think it works fine

**Comment by DaeunYim** [comment] 2021-11-08 21:03
Unable to reproduce it. Closing the issue

**Closed by DaeunYim** 2021-11-08 21:03 UTC
Labels: bug, M2
