### ISSUE TITLE
Dashboard: Database level dashboard is not showing database properties

### ISSUE THREAD

**Issue by ChrisSun-ms** [microsoft/azuredatastudio-postgresql#44] opened 2018-01-24 22:49 UTC
SQL Ops Version: 12.21.2017 - daily build
Postgres Version: 9.5

Repro Step:
(1) Open SQL Ops, connect to a PG db via connection dialog.
(2) After connect successfully, the dashboard showed up.

Expected: The dashboard shows properties of the db (Recover Model, Last Database Backup, Last Log Backup, Compatibility Level)
![image](https://user-images.githubusercontent.com/30940057/35361250-955f9160-0115-11e8-9803-7a913802dd29.png)

Fact:  The dashboard doesn't show properties of the db
![image](https://user-images.githubusercontent.com/30940057/35361301-cccaddbc-0115-11e8-956a-dfdb46fd8248.png)

**Comment by kevcunnane** [comment] 2019-04-17 21:56
👍 - I am seeing this while testing and it's very annoying. Would be nice to get the properties back.

**Comment by swjain23** [comment] 2020-02-07 22:37
Duplicate of #43

**Comment by keithnicholson** [comment] 2020-09-29 16:54
I do not see anything in the dashboard, but "Home" and the list of objects. I'm in version 1.22.  I see marked as duplicate, but it seems different.

**Comment by forivall** [comment] 2021-08-18 19:16
In my database logs, i'm seeing
```
ERROR:  column def.adsrc does not exist at character 289
STATEMENT:
  SELECT  nsp.nspname schema_name,
          cls.relname table_name,
          att.attname column_name,
          att.atttypid::regtype::text type_name,
          att.atthasdef AS has_default,
          def.adsrc as default
  FROM    pg_catalog.pg_attribute att
          INNER JOIN pg_catalog.pg_class cls
              ON att.attrelid = cls.oid
          INNER JOIN pg_catalog.pg_namespace nsp
              ON cls.relnamespace = nsp.oid
          LEFT OUTER JOIN pg_attrdef def
              ON def.adrelid = att.attrelid
              AND def.adnum = att.attnum
  WHERE   cls.relkind = ANY(ARRAY['r'])
          AND NOT att.attisdropped
          AND att.attnum  > 0
  ORDER BY 1, 2, att.attnum
```
when i open the database. probably related.

**Comment by schnoberts1** [comment] 2022-09-28 15:56
> In my database logs, i'm seeing
> 
> ```
> ERROR:  column def.adsrc does not exist at character 289
> STATEMENT:
>   SELECT  nsp.nspname schema_name,
>           cls.relname table_name,
>           att.attname column_name,
>           att.atttypid::regtype::text type_name,
>           att.atthasdef AS has_default,
>           def.adsrc as default
>   FROM    pg_catalog.pg_attribute att
>           INNER JOIN pg_catalog.pg_class cls
>               ON att.attrelid = cls.oid
>           INNER JOIN pg_catalog.pg_namespace nsp
>               ON cls.relnamespace = nsp.oid
>           LEFT OUTER JOIN pg_attrdef def
>               ON def.adrelid = att.attrelid
>               AND def.adnum = att.attnum
>   WHERE   cls.relkind = ANY(ARRAY['r'])
>           AND NOT att.attisdropped
>           AND att.attnum  > 0
>   ORDER BY 1, 2, att.attnum
> ```
> 
> when i open the database. probably related. I also dont see the database properties. PostgreSQL 13.2 (using the [`postgres:13`](https://hub.docker.com/_/postgres) docker image)

I see exactly the same thing. I noticed it as I am investigating an issue where expanding the connection in the Servers hierarchy under the Connection pane doesn't populate after disconnect then reconnect.

**Closed** 2023-08-03 18:21 UTC
Labels: wontfix
