### ISSUE TITLE
I don't see Programmability folder in Azure Data studio

### ISSUE THREAD

**Issue by pthomaz** [microsoft/azuredatastudio-postgresql#393] opened 2023-05-31 11:55 UTC
Hello everyone. I don't know if this is the correct channel to ask for help. I am not able to visualize my Storage Procedures when I use this extension for Azure Data Studio.

![image](https://github.com/microsoft/azuredatastudio-postgresql/assets/11507157/af65d020-60d9-428a-b7fa-5f8747165518)

**Comment by nasc17** [comment] 2023-06-05 22:27
Duplicate of https://github.com/microsoft/azuredatastudio-postgresql/issues/183

**Comment by nasc17** [comment] 2023-06-22 14:26
Bug has been addressed in our unstable release of PostgreSQL extension v0.4.0-insiders. We would appreciate your verification that it has been handled appropriately.

**Comment by pthomaz** [comment] 2023-06-22 14:54
> O bug foi resolvido em nossa versão instável da extensão PostgreSQL v0.4.0-insiders. Agradecemos sua verificação de que foi tratado adequadamente.

Thanks for the answer!

Apparently the "v0.4.0-insiders" version fixed the problem.

Grateful for the attention.

**Comment by nasc17** [comment] 2023-07-07 17:51
Please update to latest stable release of PostgreSQL extension v0.4.2. We would appreciate your verification if this issue is still present.

**Closed by nasc17** 2023-07-07 17:51 UTC
Labels: duplicate
